all: 
  hosts:
    dna-3-dnac.campus.wwtatc.local:
    dnac-dev.campus.wwtatc.local:
  children: 
    dnac_dev: 
      hosts: 
        dnac-dev.campus.wwtatc.local:
    dna_3:
      children: 
        dna_3_dnac: 
          hosts:
            dna-3-dnac.campus.wwtatc.local:
