#!/usr/bin/ansible-playbook
---
#
#      Copyright (c) 2019 World Wide Technology
#      All rights reserved.
#
#      author: Jeff Andiorio, jeff.andiorio@wwt.com
#
#      description: Installation Playbook for AnsibleFest 2019 Demo
#
#      usage:  ansible-playbook -i localhost installation/install.yml
#
#      inputs:
#        - bootstrap: sample_bootstrap
#

- name: Installation Playbook for AnsibleFest Demo
  hosts: localhost
  
  tasks: 
    
    - name: Create Links to Modules in Library Dir
      file: 
        state: link
        src : "{{ item }}"
        dest: ../playbooks/library/{{ item | basename }}
      with_fileglob: 
        - "../ansible-dnac-modules/*.py"

    - name: Create module_utils network/dnac directory
      file:
        path: "{{ item }}/network/dnac" 
        state: directory         
      loop: "{{ lookup('config', 'DEFAULT_MODULE_UTILS_PATH') }}"
      ignore_errors: true   

    - name: __init__.py
      file:
        path: "{{ item }}/network/dnac/__init__.py"
        state: touch
      loop: "{{ lookup('config', 'DEFAULT_MODULE_UTILS_PATH') }}"
      ignore_errors: true   
      
    - name: Copy dnac.py to module_utils/network/dnac
      copy:
        dest: "{{ item }}/network/dnac"
        src: ../ansible-dnac-modules/dnac.py
        force: yes
      loop: "{{ lookup('config', 'DEFAULT_MODULE_UTILS_PATH') }}"    
      ignore_errors: true    
    
    - name: Create Links to Inventory Plugin in inventory_plugins Dir
      file: 
        state: link
        src : "{{ item }}"
        dest: ../inventory/inventory_plugins/{{ item | basename }}
      with_fileglob: 
        - "../ansible-dnac-inventory-plugin/inventory_plugins/*"

    # The DNAC Modules have dependent third-party python modules 
    # These are installed below    
    - name: Install Dependent Python Package - timezonefinder
      pip:
        name: timezonefinder
        state: present 
        version: 3.4.2
        executable: "{{ item }}"
      loop: 
        - pip2
        - pip3

    - name: Install Dependent Python Package - geopy
      pip:
        name: geopy
        state: present 
        executable: "{{ item }}"
      loop: 
        - pip2
        - pip3

    - name: Install Dependenty Python Package - jmespath
      pip: 
        name: jmespath
        state: present
        executable: "{{ item }}"
      loop: 
        - pip2
        - pip3        
        