#!/usr/bin/ansible-playbook
---
#  usage: ansible-playbook -i inventory/hosts.yml playbooks/11-create-wireless-ssid.yml --ask-vault-pass

- name: Create Wireless SSID
  hosts: dna_3_dnac # "{{ host_groups }}"
  gather_facts: no
  connection: local

  tasks:

    - name: import creds
      include_vars:
        file: '../vars/password.yml'
      delegate_to: localhost

    - name: build wireless ssid
      dnac_wireless_ssid:
        host: "{{ inventory_hostname }}"
        port: '443'
        username: "{{ username }}"
        password: "{{ password }}"
        state: present
        #
        name: 'ANSIBLEFEST2019'
        security_level: 'WPA2_PERSONAL'
        passphrase: ANSIBLEFEST2019