#!/usr/bin/ansible-playbook
---
#  usage: ansible-playbook -i inventory/hosts.yml playbooks/12-create-wireless-profile.yml --ask-vault-pass

- name: create wireless profile using uri
  hosts: dna_3_dnac # "{{ host_groups }}"
  gather_facts: no
  connection: local

  tasks:
    - name: import creds
      include_vars:
        file: '../vars/password.yml'
      delegate_to: localhost

    - name: wireless profile
      dnac_wireless_profile:
        host: "{{ inventory_hostname }}"
        port: '443'
        username: "{{ username }}"
        password: "{{ password }}"
        state: present
        #
        name: ANSIBLEFEST_DEMO
        sites:
          - "Global/Central/Maryland Heights/ATC56"
        ssid_name: ANSIBLEFEST2019
        ssid_type: Enterprise
        flexconnect: true
        flexconnect_vlan: '30'
        fabric_enabled: false
        interface: ''