#!/usr/bin/ansible-playbook
---
#
#      Copyright (c) 2019 World Wide Technology
#      All rights reserved.
#
#      author: Jeff Andiorio, jeff.andiorio@wwt.com
#
#      description: site VLANs for AnsibleFest 2019 Demo
#
#      usage:   ansible-playbook -i inventory/inventory_plugins/dna_center.yml playbooks/5-declarative_l2_vlans.yml -e "{'host_groups':'atc56','desired_state':'present'}" --ask-vault-pass
#
#      inputs:
#        - bootstrap: sample_bootstrap
#

- name: VLANs
  hosts: "{{ host_groups }}"
  gather_facts: no 

  tasks: 

    - name: import creds
      include_vars: 
        file: '../files/password.yml'
      delegate_to: localhost  
        
    - name: import data
      include_vars: 
        file: '../vars/vlans.yml'
      delegate_to: localhost

    - name: Manage VLANs
      ios_vlan:
        state: "{{ desired_state }}"
        aggregate: "{{ vlans | list }}"
      when: 
        - os is defined
        - os == 'IOS-XE'