#!/usr/bin/ansible-playbook
---
#
#      Copyright (c) 2019 World Wide Technology
#      All rights reserved.
#
#      author: Jeff Andiorio, jeff.andiorio@wwt.com
#
#      description: BGP Config for AnsibleFest 2019 Demo
#
#      usage:  ansible-playbook -i playbooks/inventory_plugins/dna_center.yml playbooks/bgp.yml -e "{'host_groups':'atc56','desired_state':'present'}" --ask-vault-pass
#
#      inputs:
#        - host_groups: target hosts group (atc56 for demo)
#        - desired_state: [present, absent]

- name: BGP
  hosts: "{{ host_groups }}"
  gather_facts: no 

  tasks: 

    - name: import creds
      include_vars: 
        file: '../vars/password.yml'
      delegate_to: localhost  
  
    - name: import data
      include_vars: 
        file: '../vars/devices.yml'
      delegate_to: localhost
    
    - block:
      - name: Build BGP Config
        set_fact: 
          bgp_config: "{{ lookup('template', '../templates/bgp.j2').split('\n') }}"
        when: 
          - desired_state is search('present')

      - name: Config BGP 
        ios_config: 
          parents: "router bgp {{ devices[inventory_hostname_short]['bgp'].as_num }}"
          lines: "{{ bgp_config }}"
        when: 
          - desired_state is search('present')
      when: 
        - devices[inventory_hostname_short]['bgp'] is defined  

    - name: Remove Config BGP 
      ios_config: 
        lines: "no router bgp {{ devices[inventory_hostname_short]['bgp']['as_num'] }}"
      when: 
        - desired_state is search('absent') 
        - devices[inventory_hostname_short]['bgp'] is defined 