#!/usr/bin/ansible-playbook
---
#  usage: ansible-playbook -i ..inventory/hosts.yml playbooks/create-wireless-profile.yml --ask-vault-pass

- name: create wireless profile using uri
  hosts: dnac_dev # "{{ host_groups }}"
  gather_facts: no
  connection: local

  vars:

    username: andiorij
    password: 1109Wilm00reAve
    profile_body: 
      profileDetails: 
        name: "JA-Test"
        sites: 
          - "Global/Bldg56/DNAC-Dev" 
        ssidDetails: 
          - name: "JA-TEST-SSID"
            type: "Enterprise"
            enableFabric: "false"
            flexConnect: 
              enableFlexConnect: "true"
              localToVlan: "10"
            interfaceName: ""

  tasks: 
    
        #  This task is required to log into the controller and grab the auth cookie 
    # - name: login page
    #   uri:
    #     url: "https://{{inventory_hostname}}/dna/system/api/v1/auth/token"
    #     method: POST
    #     user: "{{ username }}"
    #     password: "{{ password }}"
    #     force_basic_auth: yes
    #     validate_certs: no
    #     return_content: yes
    #   register: login_results
    #   tags: backup, restore, debugging

    # - name: create wireless profile
    #   uri:
    #       url: "https://{{inventory_hostname}}/dna/intent/api/v1/wireless/profile" 
    #       body: "{{ profile_body | to_json }}"
    #       force_basic_auth: yes 
    #       user: "{{ username }}" 
    #       body_format: json
    #       password: "{{ password }}" 
    #       method: POST
    #       headers:
    #         x-auth-token: "{{ login_results.json.Token }}"
    #         __runsync: "true"
    #       timeout: 30 
    #       status_code: 202 
    #       return_content: no
    #       validate_certs: no 
    #   register: results

    # - debug: var=results

    - name: wireless profile 
      dnac_wireless_profile:
        host: "{{ inventory_hostname }}"
        port: '443'
        username: "{{ username }}"
        password: "{{ password }}"
        state: absent
        #
        name: WP-ATC56-DNAC-DEV
        sites:          
          - "Global/Bldg56/DNAC-Dev"      
        ssid_name: DNA3_DNAC
        ssid_type: Enterprise
        flexconnect: true
        flexconnect_vlan: '10'
        fabric_enabled: false
        interface: ''
      tags: [dna-3-dnac]

    - name: wireless profile 
      dnac_wireless_profile:
        host: "{{ inventory_hostname }}"
        port: '443'
        username: "{{ username }}"
        password: "{{ password }}"
        state: present
      
        #
        name: "DEV-DNAC"
        sites:          
          - "Global/Bldg56/DNAC-Dev"
        ssid_name: "DEV-DNAC"
        ssid_type: Enterprise
        flexconnect: false
        # flexconnect_vlan: '10'
        fabric_enabled: false
        interface: 'EFT-Clients'
      tags: [dnac-dev]
        