#!/usr/bin/ansible-playbook 
---

# ansible-playbook -i playbooks/inventory_plugins/dna_center.yml playbooks/declarative_l2_vlans.yml -e "{'host_groups':'atc56','desired_state':'present'}" --ask-vault-pass

- name: VLANs
  hosts: "{{ host_groups }}"
  gather_facts: no 

  tasks: 

    - name: import creds
      include_vars: 
        file: '../files/password.yml'
      delegate_to: localhost  
        
    - name: import data
      include_vars: 
        file: '../vars/vlans.yml'
      delegate_to: localhost

    - name: Manage VLANs
      ios_vlan:
        state: "{{ desired_state }}"
        purge: yes
        aggregate: "{{ vlans | list }}"
      when: ansible_network_os == 'ios'