- name: import creds
  include_vars: 
    file: '../vars/password.yml'
  delegate_to: localhost  

- name: import data
  include_vars: 
    file: '../vars/lab_vars.yml'
    # name: lab_vars
  delegate_to: localhost