---
- name: Layer 2 Access Ports 
  hosts: "{{ host_groups }}"
  gather_facts: no 

  tasks: 

    - name: import creds
      include_vars: 
        file: '../files/password.yml'
      delegate_to: localhost  
        
    - name: import data
      include_vars: 
        file: '../files/lab_vars.yml'
        name: lab_vars
      delegate_to: localhost

    - name: Config L2 Access Interfaces
      ios_l2_interface:
          name: "{{ item.name }}" 
          state: "{{ desired_state }}" 
          mode: "{{ item.mode }}" 
          access_vlan: "{{ item.access_vlan }}"
      loop: "{{ lab_vars[inventory_hostname_short]['l2_interfaces'] }}"
      when: 
        - item['mode'] is search('access')

