---
- name: VLANs
  hosts: "{{ host_groups }}"
  gather_facts: no 

  tasks: 

    - name: import creds
      include_vars: 
        file: '../files/password.yml'
      delegate_to: localhost  

    - name: import data
      include_vars: 
        file: '../files/lab_vars.yml'
        name: lab_vars
      delegate_to: localhost
    
    - name: Manage VLANs
      ios_vlan:
        vlan_id: "{{ item.id }}" 
        name: "{{ item.name }}" 
        state: "{{ desired_state }}"
      loop: "{{ lab_vars['vlans'] }}"

    - name: Spanning Tree Priority 
      ios_config: 
        lines: 
          - spanning-tree vlan 1-4094 priority {{ lab_vars[inventory_hostname_short]['stp_priority'] }}
      when: 
        - lab_vars[inventory_hostname_short]['role'] is search('distribution')
        - desired_state is search('present')