- name: VLANs
  hosts: "{{ host_groups }}"
  gather_facts: no 

  vars: 
    vlans: 
      - {'name':'vlan_10','vlan_id':10}
      - {'name':'vlan_20','vlan_id':20}
      - {'name':'vlan_30','vlan_id':30}
      # - {'name':'vlan_40','vlan_id':40}
      - {'name':'underlay_vlan','vlan_id':2001}
  tasks: 

    - name: import creds
      include_vars: 
        file: '../files/password.yml'
      delegate_to: localhost  

    - name: import data
      include_vars: 
        file: '../files/lab_vars.yml'
        name: lab_vars
      delegate_to: localhost


    - name: Manage VLANs
      ios_vlan:
        state: present
        purge: yes
        aggregate: 
          - {'name':'vlan_10','vlan_id':10}
          - {'name':'vlan_20','vlan_id':20}
          - {'name':'vlan_30','vlan_id':30}
          # - {'name':'vlan_40','vlan_id':40}
          - {'name':'underlay_vlan','vlan_id':2001}